"""SeqAtelierの全サブパッケージが共有する基盤: 型・例外、GenBank I/O、配列インデックス。"""

from __future__ import annotations

from seqatelier.core.index import (
    INDEX_FIELDS,
    add_entry,
    list_entries,
    load_index,
    register_from_genbank,
    remove_entry,
    save_index,
    search,
)
from seqatelier.core.sequence import SEQATELIER_NOTE_PREFIX, LabRecord, parse_seqatelier_note, resolve_site
from seqatelier.core.types import (
    CodonHost,
    CodonOptimizationError,
    CodonOptimizationIssue,
    CodonOptimizationResult,
    FeatureLocation,
    FeatureNotFoundError,
    IndexEntry,
    InFusionDesign,
    InFusionReactionConditions,
    LinearMap,
    LinearMapLine,
    MutationType,
    Primer,
    PrimerDesignError,
    PrimerPair,
    PurificationGrade,
    QuikChangeDesign,
    SeqAtelierError,
    SequenceFeature,
    SequenceIndexError,
    SequenceValidationError,
    Strand,
)

__all__ = [
    "INDEX_FIELDS",
    "SEQATELIER_NOTE_PREFIX",
    "CodonHost",
    "CodonOptimizationError",
    "CodonOptimizationIssue",
    "CodonOptimizationResult",
    "FeatureLocation",
    "FeatureNotFoundError",
    "IndexEntry",
    "InFusionDesign",
    "InFusionReactionConditions",
    "SeqAtelierError",
    "LabRecord",
    "LinearMap",
    "LinearMapLine",
    "MutationType",
    "Primer",
    "PrimerDesignError",
    "PrimerPair",
    "PurificationGrade",
    "QuikChangeDesign",
    "SequenceFeature",
    "SequenceIndexError",
    "SequenceValidationError",
    "Strand",
    "add_entry",
    "list_entries",
    "load_index",
    "parse_seqatelier_note",
    "register_from_genbank",
    "remove_entry",
    "resolve_site",
    "save_index",
    "search",
]
